[features]
seeds = false
skip-lint = false
[programs.localnet]
solvoucher = "DtDGo9RPBKmVcFKBxBTMzVs6ckQ5bRnrzW1FPYPEEZAq"

[programs.devnet]
solvoucher = "DtDGo9RPBKmVcFKBxBTMzVs6ckQ5bRnrzW1FPYPEEZAq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
