[features]
seeds = false
skip-lint = false
[programs.localnet]
solvoucher = "DX8ZhZ1nqr1LRt8hHd3aeobqpg9FgvCJRSBwG9M4Y7DA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/grrwahrr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
